version: '3.1'

services:
  mysql:
    image: 'mysql:8.0.22'
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root

    ports:
      - '3307:3306'
